name: zhangsan
#对象配置
person:
  name: zhuangsan
  age: 13
  sex: 男
#行内对象配置
person1: {name: zhuang,age: 32,sex: 女}
server:
  port: 8082

#配置数据、集合
city:
  - beijin
  - tianjin
  - chongqin
  - wuhan
city1: [beijin,tianjin,chongqin,wuhan]

#集合中对象
student:
  - name: haha
    age: 24
    add: tianjin
  - name: lucy
    age: 16
    add: yaowei
student1: [{name: haha,age: 24,add: tianjin},{name: lucy,age: 16,add: yaowei}]