server:
  port: 7003
spring:
  application:
    name: stream_consumer
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
  cloud:
    stream:
      instanceCount: 2
      instanceIndex: 1
      bindings:
        input: #内置消息通道，从itcast-default中获取消息
          destination: itcast-default
        myinput:
          destination: itcast-custom-output
          group: group1
          consumer:
            partitioned: true
      binders:
        defaultRabbit:
          type: rabbit