server:
  port: 7001
spring:
  application:
    name: stream_producer
  rabbitmq:
    addresses: localhost
    host: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: itcast-default #指定消息改送的目的地
        myoutput:
          destination: itcast-custom-output
          producer:
            partition-key-expression: payload  #表达式规则
            partition-count: 2
      binders:  #配置绑定器
        defaultRabbit:
          type: rabbit
